function [fitresult, gof] = createFit5(V, i_447_1)
%CREATEFIT5(V,I_447_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: i_447_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Dec-2022 11:23:56


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, i_447_1 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.989287124955403;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

h = plot( fitresult,'b', xData, yData,'.b');

grid on


