function [fitresult, gof] = createFit1(V, i_532)
%CREATEFIT1(V,I_532)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: i_532
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2022 00:29:35


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, i_532 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.982459356724425;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

h = plot( fitresult,'g', xData, yData,'.g' );
% Label axes

grid on


