function [fitresult, gof] = createFit2(V, i_447)
%CREATEFIT2(V,I_447)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: i_447
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2022 00:35:55


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, i_447 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99347480792124;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
h = plot( fitresult,'b', xData, yData ,'.b');

grid on


