function [fitresult, gof] = createFit4(V, i_532_1)
%CREATEFIT4(V,I_532_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : V
%      Y Output: i_532_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Dec-2022 11:00:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( V, i_532_1 );

% Set up fittype and options.
ft = fittype( 'sin3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [4.99999780246533 0.628318530717959 0.112768621705557 1.52074286165497 1.25663706143592 3.07564440861483 0.517886026624483 2.51327412287183 -2.36580755661556];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

h = plot( fitresult,'g', xData, yData,'.g');

grid on


